v1.1.2
watermelontools/wm-extension pull request #148
Opened 2022-04-26 14:57 UTC by EstebanDalelR

v1.1.2

2022-04-26 15:08 UTC, baristaGeek requested changes
Just one very minor observation:

When you click "Get help on Slack" after running "Run Watermelon", nothing happens. To solve this, you can either solve it by adding the correct event handler, or simply by removing the button.

Whatever you want.

2022-04-26 19:19 UTC, EstebanDalelR commented
> Just one very minor observation:
> 
> When you click "Get help on Slack" after running "Run Watermelon", nothing happens. To solve this, you can either solve it by adding the correct event handler, or simply by removing the button.
> 
> Whatever you want.

Please @baristaGeek explain further, does this happen on error or on result?

2022-04-26 22:13 UTC, baristaGeek commented
> > Just one very minor observation:
> > When you click "Get help on Slack" after running "Run Watermelon", nothing happens. To solve this, you can either solve it by adding the correct event handler, or simply by removing the button.
> > Whatever you want.
> 
> Please @baristaGeek explain further, does this happen on error or on result?

On result

2022-04-27 14:47 UTC, baristaGeek approved these changes

2022-04-27 14:52 UTC, merged