Pass logos
watermelontools/wm-extension pull request #176
Opened 2022-05-02 17:09 UTC by EstebanDalelR

## Description

Dynamically changes logos according to the user's prefers-color-scheme

## Type of change

- Feature

![image](https://user-images.githubusercontent.com/11527621/166292696-abb25570-f1e5-41bb-bf02-da65e98db541.png)
![image](https://user-images.githubusercontent.com/11527621/166292727-190ec144-5c0e-446d-b819-e32bdb9ed785.png)

2022-05-02 17:09 UTC, EstebanDalelR commented on src/extension.ts
> +  var packageFile = JSON.parse(fs.readFileSync(extensionPath, "utf8"));
Formatting only

2022-05-03 16:56 UTC, baristaGeek requested changes
Nice, but logo looks huge. Please resize

2022-05-03 17:17 UTC, EstebanDalelR commented
> Nice, but logo looks huge. Please resize

There were no changes in it's CSS. Care to provide screenshots?

2022-05-04 02:50 UTC, baristaGeek commented
Before this PR
<img width="531" alt="Screen Shot 2022-05-03 at 9 49 38 PM" src="https://user-images.githubusercontent.com/8325094/166617240-bf580a48-cc7d-43c7-9125-9c2ecd74d395.png">

After this PR
<img width="484" alt="Screen Shot 2022-05-03 at 9 50 01 PM" src="https://user-images.githubusercontent.com/8325094/166617259-62eaed6f-fc60-4ad5-b9e9-5c0c3fb9785f.png">

2022-05-04 16:19 UTC, EstebanDalelR commented
I've set it to the same 300px @baristaGeek

2022-05-04 19:23 UTC, merged